# Generated by Django 2.2.5 on 2022-04-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_page', '0002_auto_20220413_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_year',
            field=models.IntegerField(),
        ),
    ]
