# Generated by Django 2.2.5 on 2022-04-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_page', '0004_auto_20220413_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='course',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_year',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=16),
        ),
    ]
