# Generated by Django 2.2.5 on 2022-04-13 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_page', '0005_auto_20220413_1404'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
