# Generated by Django 2.2.5 on 2022-04-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_page', '0007_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='end_year',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='start_year',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
