# Generated by Django 2.2.5 on 2022-04-13 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_page', '0008_auto_20220413_1600'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
