# Generated by Django 2.2.5 on 2022-04-14 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_page', '0010_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=16, verbose_name='课程代码'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.CharField(max_length=16, verbose_name='课程ID'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=32, verbose_name='课程名称'),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(max_length=16, verbose_name='学期'),
        ),
        migrations.CreateModel(
            name='CanvasUserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canvas_id', models.CharField(max_length=32, unique=True, verbose_name='Canvas ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('physical_id', models.CharField(max_length=32, unique=True, verbose_name='学号/工号')),
                ('origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='course_page.Course')),
            ],
        ),
    ]
