# Generated by Django 2.2.5 on 2022-04-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_page', '0011_auto_20220414_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=16, verbose_name='课程代码'),
        ),
    ]
